### ISSUE TITLE
anti afk

### ISSUE THREAD

**Issue by esruv** [antoinedelia/fortnite-impostor-bot#1]
does this work still since they added anti-afk detection also how safe is it?

**Comment by antoinedelia** [comment]
Hey, thanks for being interested in the code!

I've used this script on many games, and no trouble so far. As you are not using any cheat mechanism, it should be fine.

As for the anti-afk detection, Fortnite wants you to do one of these 3 things to be sure you're active: move to a different room, do a task, or use an emote. So I've just added a feature that will move your character or emote at random. So you will still be able to gain full XP.

Hope that helped!
